name: adminsd46
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_lints: ^3.0.0
  http: ^1.1.0
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  